AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for WordPress instance setup with IAM role."

Resources:
  WebServer:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-12345678"  # Replace with a valid AMI ID
      IamInstanceProfile: !Ref WebServerIAMInstanceProfile
      Tags:
        - Key: "Name"
          Value: "WordPressServer"

  WebServerIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "WordPressServerPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "ec2:DescribeInstances"
                  - "ec2:StartInstances"
                  - "ec2:StopInstances"
                Resource: "*"

  WebServerIAMInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref WebServerIAMRole
